# Global Power Plant

## Geospatial Visualization with Plotly

In [ ]:
#-----------------------------------------------------------------------------------------
# Name:        Practice Day 6
# Author:      Erick Rico
# Created:     08/08/2025
#-----------------------------------------------------------------------------------------

In [1]:
import pandas as pd
import plotly.express as px

In [2]:
df = pd.read_csv("global_power_plant_database.csv")

In [4]:
print(df.shape)
df.head()

(29910, 24)

,country,country_long,name,gppd_idnr,capacity_mw,latitude,longitude,primary_fuel,other_fuel1,other_fuel2,...,url,geolocation_source,wepp_id,year_of_capacity_data,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh
0,AFG,Afghanistan,Kajaki Hydroelectric Power Plant Afghanistan,GEODB0040538,33.00,32.3220,65.1190,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009793,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Afghanistan,Mahipar Hydroelectric Power Plant Afghanistan,GEODB0040541,66.00,34.5560,69.4787,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009795,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Afghanistan,Naghlu Dam Hydroelectric Power Plant Afghanistan,GEODB0040534,100.00,34.6410,69.7170,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009797,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Afghanistan,Nangarhar (Darunta) Hydroelectric Power Plant ...,GEODB0040536,11.55,34.4847,70.3633,Hydro,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,1009787,2017.0,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Afghanistan,Northwest Kabul Power Plant Afghanistan,GEODB0040540,42.00,34.5638,69.1134,Gas,NaN,NaN,...,http://globalenergyobservatory.org,GEODB,NaN,2017.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29910 entries, 0 to 29909
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   country                   29910 non-null  object
 1   country_long              29910 non-null  object
 2   name                      29910 non-null  object
 3   gppd_idnr                 29910 non-null  object
 4   capacity_mw               29910 non-null  float64
 5   latitude                  29910 non-null  float64
 6   longitude                 29910 non-null  float64
 7   primary_fuel              29910 non-null  object
 8   other_fuel1               1963 non-null   object
 9   other_fuel2               303 non-null    object
 10  other_fuel3               104 non-null    object
 11  commissioning_year        16303 non-null  float64
 12  owner                     19531 non-null  object
 13  source                    29895 non-null  object
 14  url                       29892 non-null  object
 15  geolocation_source        29491 non-null  object
 16  wepp_id                   16381 non-null  object
 17  year_of_capacity_data     13743 non-null  float64
 18  generation_gwh_2013       6996 non-null   float64
 19  generation_gwh_2014       7440 non-null   float64
 20  generation_gwh_2015       8144 non-null   float64
 21  generation_gwh_2016       8971 non-null   float64
 22  generation_gwh_2017       9213 non-null   float64
 23  estimated_generation_gwh  21791 non-null  float64
dtypes: float64(11), object(13)
memory usage: 5.5+ MB

In [6]:
df.columns

Index(['country', 'country_long', 'name', 'gppd_idnr', 'capacity_mw',
       'latitude', 'longitude', 'primary_fuel', 'other_fuel1', 'other_fuel2',
       'other_fuel3', 'commissioning_year', 'owner', 'source', 'url',
       'geolocation_source', 'wepp_id', 'year_of_capacity_data',
       'generation_gwh_2013', 'generation_gwh_2014', 'generation_gwh_2015',
       'generation_gwh_2016', 'generation_gwh_2017',
       'estimated_generation_gwh'],
      dtype='object')

In [19]:
energy = df[["name", "country", "capacity_mw", "latitude", "longitude", "primary_fuel"]].copy()
energy.sample(5)

,name,country,capacity_mw,latitude,longitude,primary_fuel
1514,Catas Altas I,BRA,4.0,-24.5972,-49.1350,Hydro
72,ATUCHA I,ARG,370.0,-33.9670,-59.2059,Nuclear
4305,Saint-Lambert,CAN,5.8,45.4959,-73.5153,Hydro
29036,Warrior Ridge Hydro,USA,2.8,40.5400,-78.0346,Hydro
24964,Koppelman Sun CSG,USA,5.0,44.1826,-93.8763,Solar

In [20]:
print(energy["primary_fuel"].nunique())
common_fuels = energy["primary_fuel"].value_counts()
common_fuels

15

primary_fuel
Hydro             7155
Solar             5929
Wind              5188
Gas               3922
Coal              2390
Oil               2290
Biomass           1396
Waste             1087
Nuclear            198
Geothermal         189
Storage             58
Other               44
Cogeneration        41
Petcoke             13
Wave and Tidal      10
Name: count, dtype: int64

In [21]:
# Quitando tipos de energía no tan comunes
common_fuels = common_fuels[common_fuels > 100].index
energy = energy[energy["primary_fuel"].isin(common_fuels)].copy()
energy["primary_fuel"].value_counts()

primary_fuel
Hydro         7155
Solar         5929
Wind          5188
Gas           3922
Coal          2390
Oil           2290
Biomass       1396
Waste         1087
Nuclear        198
Geothermal     189
Name: count, dtype: int64

In [22]:
energy.head()

,name,country,capacity_mw,latitude,longitude,primary_fuel
0,Kajaki Hydroelectric Power Plant Afghanistan,AFG,33.00,32.3220,65.1190,Hydro
1,Mahipar Hydroelectric Power Plant Afghanistan,AFG,66.00,34.5560,69.4787,Hydro
2,Naghlu Dam Hydroelectric Power Plant Afghanistan,AFG,100.00,34.6410,69.7170,Hydro
3,Nangarhar (Darunta) Hydroelectric Power Plant ...,AFG,11.55,34.4847,70.3633,Hydro
4,Northwest Kabul Power Plant Afghanistan,AFG,42.00,34.5638,69.1134,Gas

In [ ]:
scat_map = px.scatter_mapbox(energy,
                             lat="latitude", 
                             lon="longitude", 
                             color="primary_fuel",
                             hover_name="name",
                             hover_data={"country", "capacity_mw"},
                             size="capacity_mw", # escalar el tamaño por capacidad
                             size_max=10), # ajustar el tamaño máximo de los puntos
                            #  mapbox_style="open-street-map")
# scat_map.update_layout(mapbox_center={"lat": 0, "lon": 0},
#                        mapbox_zoom=0.5,
#                        title_text="Distribución de Plantas de Energía Globales",
#                        title_x=0.5)

# scat_map.show()

# Comentado para evitar que el scatter_map haga que se trabe mi VSCode

**Conclusiones del mapa de plantas de energía globales:**

- Se observa una alta concentración de plantas en el este de Estados Unidos y el este de China, lo que refleja la densidad poblacional y la demanda energética en esas regiones.
- En Asia, especialmente en China e India, predomina el uso de carbón (“coal”), mientras que en Brasil, Canadá y también en China destaca la energía hidroeléctrica (“hydro”), probablemente por la presencia de grandes presas.
-En Europa y Estados Unidos hay una mayor diversidad de fuentes de energía, incluyendo nuclear, eólica (“wind”), solar y biomasa, lo que indica una matriz energética más diversificada y una mayor adopción de energías limpias.
Japón también muestra una presencia relevante de energía nuclear y renovable.
- En el Medio Oriente predominan las plantas de gas y petróleo (“gas” y “oil”), lo cual es coherente con la disponibilidad de estos recursos en la región.
- Aunque la energía solar es la segunda más común según los datos, en el mapa no es tan notoria visualmente, posiblemente porque las plantas solares suelen tener menor capacidad individual o están más dispersas.
- La energía eólica (“wind”) es claramente visible en regiones como el norte de Europa y partes de China.
- La distribución de tipos de energía varía mucho por región, reflejando tanto la disponibilidad de recursos naturales como las políticas energéticas locales.

En resumen, el mapa permite identificar patrones regionales claros en el uso de fuentes de energía y la concentración de plantas, así como la transición hacia una matriz más diversificada en algunas regiones del mundo.